Repository owncloud/notifications, pull requests merged in 2018-08, with the labels that each got.

#216 Use core run.sh to run webUI acceptance tests
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/run.sh
Labels: 3 - To Review

#222 Remove unneeded SKELETON_DIR in .drone.yml
  .drone.yml
Labels: 3 - To Review

#224 [stable10] acceptance test backports
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiNotifications/delete-notifications.feature
  tests/acceptance/features/apiNotifications/email-notifications.feature
  tests/acceptance/features/apiNotifications/notifications-content.feature
  tests/acceptance/features/apiNotifications/statuscodes.feature
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#226 [stable10] Remove resetAppConfigs - it is not needed here
  tests/acceptance/features/bootstrap/NotificationsContext.php
Labels: 3 - To Review, dev:acceptance-tests

#227 Accceptance test code standard
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 3 - To Review, dev:acceptance-tests

#223 [stable10] Backport of Clear user notifications from table after they…
  appinfo/app.php
  lib/AppInfo/Application.php
  lib/Handler.php
  tests/Unit/AppInfo/ApplicationTest.php
  tests/Unit/HandlerTest.php
Labels: 3 - To Review

#229 [stable10] UI test to check correctness of the link
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/lib/Notification.php
  tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
Labels: 3 - To Review, dev:acceptance-tests

#231 add PHP 7.2 for unit tests
  .drone.yml
Labels: 3 - To Review, QA-team

#232 add PHP7.2 to stable10
  .drone.yml
Labels: 3 - To Review, QA-team
