Repository owncloud/notifications, pull requests merged in 2018-11, with the labels that each got.

#248 Allow max-version 11.0.0.* so CI runs for developers
  appinfo/info.xml
Labels: 3 - To Review, QA-team

#250 Make compatible with 11+
  appinfo/info.xml
Labels: 3 - To Review

#251 [stable10] Set max version to 10
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review

#253 Adjust user creation test steps
  tests/acceptance/features/apiNotifications/delete-notifications.feature
  tests/acceptance/features/apiNotifications/notifications-content.feature
  tests/acceptance/features/apiNotifications/statuscodes.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests
