Repository owncloud/notifications, pull requests merged in 2018-06, with the labels that each got.

#189 Fix notification not being sent by email if system cron is set
  lib/Mailer/NotificationMailer.php
Labels: 3 - To Review, backport-request, bug

#187 Adjust email message
  lib/Mailer/NotificationMailer.php
  lib/Mailer/NotificationMailerAdapter.php
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
  tests/Unit/Mailer/NotificationMailerAdapterTest.php
  tests/Unit/Mailer/NotificationMailerTest.php
  tests/acceptance/features/apiNotifications/email-notifications.feature
Labels: 3 - To Review, backport-request

#188 [stable10] Adjust email message
  lib/Mailer/NotificationMailer.php
  lib/Mailer/NotificationMailerAdapter.php
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
  tests/Unit/Mailer/NotificationMailerAdapterTest.php
  tests/Unit/Mailer/NotificationMailerTest.php
Labels: 3 - To Review

#196 Remove acceptance test code that was moved into core
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
  tests/acceptance/features/lib/Notification.php
  tests/acceptance/features/lib/NotificationsAppDialog.php
  tests/acceptance/features/lib/NotificationsEnabledOwncloudPage.php
Labels: 3 - To Review

#194 Fix migration from 8.2.11 to 10.0.x with postgresql
  appinfo/Migrations/Version20180604132522.php
Labels: 3 - To Review, backport-request

#195 [stable10] Fix migration from 8.2.11 to 10.0.x with postgresql
  appinfo/Migrations/Version20180604132522.php
Labels: 3 - To Review

#199 [stable10] Remove acceptance test code that was moved into core
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
  tests/acceptance/features/lib/NotificationsAppDialog.php
  tests/acceptance/features/lib/NotificationsEnabledOwncloudPage.php
Labels: 3 - To Review

#193 Cleanup drone yml
  .drone.yml
Labels: 3 - To Review

#201 [stable10] Cleanup drone yml
  .drone.yml
Labels: 3 - To Review

#204 [stable10] Increase version to 0.3.4 + changelog
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review, backport-request

#203 Version increase for recent changes
  appinfo/info.xml
Labels: 3 - To Review

#207 [Stable10] Add common footer to notifications
  appinfo/info.xml
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
Labels: 3 - To Review

#208 Add "hello" in the mail templates
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
Labels: 3 - To Review

#209 Add "hello" in the mail templates
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
Labels: 3 - To Review

#210 Include the product name in the mail for the notifications
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
  tests/acceptance/features/apiNotifications/email-notifications.feature
Labels: 3 - To Review

#211 [stable10] Include the product name in the mail for the notifications
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
  tests/acceptance/features/apiNotifications/email-notifications.feature
Labels: 3 - To Review
