Repository owncloud/notifications, pull requests merged in 2018-09, with the labels that each got.

#233 [stable10] Backport translations from master, initial version
  l10n/.tx/config
  l10n/cs_CZ.js
  l10n/cs_CZ.json
  l10n/de.js
  l10n/de.json
  l10n/de_DE.js
  l10n/de_DE.json
  l10n/es.js
  l10n/es.json
  l10n/eu.js
  l10n/eu.json
  l10n/fr.js
  l10n/fr.json
  l10n/id.js
  l10n/id.json
  l10n/pt_BR.js
  l10n/pt_BR.json
  l10n/ru.js
  l10n/ru.json
  l10n/sq.js
  l10n/sq.json
  l10n/th_TH.js
  l10n/th_TH.json
Labels: 3 - To Review

#234 [stable10] Changelog for 0.3.5
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To Review

#230 su-exec www-data is not needed for acceptance tests
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#236 [stable10] su-exec www-data is not needed for acceptance tests
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#237 Register Symfony listener for testing events
  tests/Unit/AppInfo/ApplicationTest.php
Labels: backport-request, p2-high

#238 [stable10] Register Symfony listener for testing events
  CHANGELOG.md
  tests/Unit/AppInfo/ApplicationTest.php
Labels: 4 - To release
