Repository owncloud/notifications, pull requests merged in 2018-04, with the labels that each got.

#155 Move tests to drone
  .drone.yml
  .travis.yml
  Makefile
  tests/acceptance/composer.json
  tests/acceptance/config/behat.yml
  tests/acceptance/features/lib/NotificationsAppDialog.php
  tests/acceptance/features/lib/NotificationsEnabledOwncloudPage.php
  tests/acceptance/run.sh
Labels: 3 - To Review

#163 Reformat to phpcs standard
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
Labels: 3 - To Review

#167 Include the template folder in the Makefile
  Makefile
Labels: 3 - To Review, backport-request, p1-urgent

#162 [stable10] Email templates
  lib/Mailer/NotificationMailer.php
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
Labels: 3 - To Review

#157 Use email templates to generate the mail messages
  lib/Mailer/NotificationMailer.php
  templates/mail/htmlmail.php
  templates/mail/plaintextmail.php
Labels: 3 - To Review

#168 [stable10] Include the template folder in the Makefile
  Makefile
Labels: 3 - To Review, p1-urgent

#170 Fix app loading
  appinfo/app.php
  lib/AppInfo/Application.php
Labels: 3 - To Review

#173 Allow CORS requests to list notifications
  lib/Controller/EndpointController.php
Labels: 3 - To Review

#176 [stable10] Allow CORS requests to list notifications
  lib/Controller/EndpointController.php
Labels: 3 - To Review

#174 Change log messages for better debugging
  lib/Mailer/NotificationMailerAdapter.php
  tests/Unit/Mailer/NotificationMailerAdapterTest.php
Labels: 3 - To Review

#165 scrutinizer upload
  .drone.yml
Labels: 3 - To Review

#178 delete unneeded mailhog url
  tests/acceptance/config/behat.yml
Labels: 3 - To Review

#179 occ: Provide argument for link
  lib/Command/Generate.php
Labels: 3 - To Review

#181 [stable10] delete unneeded mailhog url
  tests/acceptance/config/behat.yml
Labels: 3 - To Review

#180 Update changelog for 0.3.3 / 10.0.8
  CHANGELOG.md
Labels: 3 - To Review

#177 acceptance tests for email notifications
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiNotifications/email-notifications.feature
  tests/acceptance/features/bootstrap/NotificationsContext.php
  tests/acceptance/run.sh
Labels: 3 - To Review

#182 improve error reporting in acceptance tests
  tests/acceptance/features/bootstrap/NotificationsContext.php
Labels: 3 - To Review
