Repository owncloud/notifications, pull requests merged in 2019-04, with the labels that each got.

#269 Phpunit 5 6
  composer.lock
  lib/AppInfo/Application.php
  lib/Controller/EndpointController.php
  lib/Mailer/NotificationMailer.php
  lib/Mailer/NotificationMailerAdapter.php
  phpunit.xml
  tests/Unit/AppInfo/AppTest.php
  tests/Unit/AppInfo/ApplicationTest.php
  tests/Unit/AppTest.php
  tests/Unit/Command/GenerateTest.php
  tests/Unit/Controller/EndpointControllerTest.php
  tests/Unit/HandlerTest.php
  tests/Unit/Mailer/NotificationMailerTest.php
  tests/acceptance/features/bootstrap/NotificationsContext.php
Labels: 3 - To Review, QA-team

#272 Fix makefile for tar format and excluded files
  Makefile
Labels: 4 - To release

#273 [stable10] Backport waiting PRs as at 2019-04-03
  Makefile
  composer.lock
  lib/AppInfo/Application.php
  lib/Controller/EndpointController.php
  lib/Mailer/NotificationMailer.php
  lib/Mailer/NotificationMailerAdapter.php
  phpunit.xml
  tests/Unit/AppInfo/AppTest.php
  tests/Unit/AppInfo/ApplicationTest.php
  tests/Unit/AppTest.php
  tests/Unit/Command/GenerateTest.php
  tests/Unit/Controller/EndpointControllerTest.php
  tests/Unit/HandlerTest.php
  tests/Unit/Mailer/NotificationMailerTest.php
  tests/acceptance/features/apiNotifications/email-notifications.feature
  tests/acceptance/features/bootstrap/NotificationsContext.php
Labels: 4 - To release, QA-team

#274 [stable10] Remove acceptance test code moved into core
  tests/acceptance/features/lib/Notification.php
Labels: 3 - To Review, QA-team

#275 [stable10] Fixes #129 - only set icon in case an icon is available
  lib/Handler.php
Labels: 3 - To Review

#280 Release 0.5.0
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To Review
